### ISSUE TITLE
Back-End Requirements: 

### ISSUE THREAD

**Issue by pkusoglu** [Team-Avengineers/WellMap#25]
More well groups are needed to be added (phpMyAdmin), will use Ajax to link the database to the front end
Save and load data in json

**Comment by dtfsheedy** [comment]
I think that this is basically done. The one feature I'm unsure on right now is how to best pass the data from the c# function to the javascript. currently, the c# code puts the db info into an array of structs but I'm not sure how that should be returned to the java. Ajax functions are mostly done other than that

**Comment by jenniferjen** [comment]
Please refer to Early tasks for Software Engineers
