### ISSUE TITLE
CHARTS

### ISSUE THREAD

**Issue by TConX** [Team-Avengineers/WellMap#32]
Data visualization means charts.  This means figuring out a way to grab information currently held in the layer objects and rendering it out as a chart.  But how do you make charts?

I'm going to suggest chart.js ( http://www.chartjs.org/ ).  It's got a bunch of different chart types and provides documentation on how to make them, mostly by throwing Javascript objects into them.

Maybe I'll upload the library tonight and try making a simple bargraph...

**Comment by TConX** [comment]
Uploaded.  Maybe play with these later...

**Comment by jenniferjen** [comment]
Not in scope of project - Low Priority
