### ISSUE TITLE
Programming Items to TODO for Non-Software Members

### ISSUE THREAD

**Issue by jenniferjen** [Team-Avengineers/WellMap#33]
First Priority: **ONLY FOCUS ON THESE ITEMS**
-Import/Export Excel -> Jennifer & Piril - DONE
-Set new map to open in new tab -> Ben -> DONE
-Compare well lists -> John 
-Ability to create multiple lists -> Ben & Chris - DONE
-Leave sidebar out -> Jennifer passing off to Toss due to different styles in css file - > DONE
-Get rid of settings button (replaced with Edit>Map info) -> Jennifer - DONE

Items not a priority at all:
-Chart functionality

**Anyone not assigned to tasks above please refer to presentation and final report TODO issue**

**Comment by jenniferjen** [comment]
Functions to read and write for import/excel file has been created and work BUT they depend on the database and selecting wells so I've worked on them as far as I can go..I'm going to pass the rest of the needed functionality to Daniel

**Comment by TConX** [comment]
**Import/Export**

This looks like a start:
http://stackoverflow.com/questions/8238407/how-to-parse-excel-file-in-javascript-html5
http://oss.sheetjs.com/js-xls/

Once you import an XLS and convert it to a JSON string, you just use JSON.parse() to turn it into an object literal.  After that, you can just for-loop through it to make actual objects.

**Comment by jenniferjen** [comment]
Import and Export are complete
