### ISSUE TITLE
Early Tasks for Software Engineer (DATABASE ITEMS)

### ISSUE THREAD

**Issue by jenniferjen** [Team-Avengineers/WellMap#34]
ONLY THESE ITEMS SHOULD BE FOCUSED ON
-Must be able to access a fully functional comprehensive database:
        -In addition to lat and long add dummy company names and production data with units 
-Ability to select multiple wells

**Comment by TConX** [comment]
**Ability to select multiple wells**

I just got select by click working, and you can select multiple.  Are we talking select by area?

**In addition to lat and long add dummy company names and production data with units**

There's an object in map_objects.js -> Point called wellData.  It's empty right now, but putting anything in there is just a matter of:

    the_map.layers[i].points[j].wellData.PROPERTY = value;

**Comment by TConX** [comment]
Still need to make that Select By Area

**Comment by TConX** [comment]
Select by Area is working.
