### ISSUE TITLE
Later Tasks for Software Engineers 

### ISSUE THREAD

**Issue by jenniferjen** [Team-Avengineers/WellMap#35]
FOCUS ON THESE ITEMS FIRST
-Getting layers to work on the sidebar (ie. be able to select and deselect specific company points)
-Changing well icon colour to match companies
-Generate UWI grid
-Keeping sidebar out no ui button required to open it

**Comment by TConX** [comment]
**Getting layers to work on the sidebar**

Not completely sure I understand this one.  Is this selecting individual wells by clicking on them from the layer list?

**Changing well icon colour to match companies**

[Something like these?](http://www.benjaminkeen.com/google-maps-coloured-markers/)

**Generate UWI grid**

There's an XML-like data format called KML/KMZ that is used to display Geographical Data.  You can throw it right into Google Maps with a ' .loadFromKML({url: "address of kml data"}) '.

The hard part is finding a KML file that has a full UWI grid.  I just added an NTS grid to the application that I [got from the Alberta Geological Survey](http://www.ags.gov.ab.ca/gis/map_converters/conversion_tools.html).  It's obviously incomplete, but demonstrates the idea.

**Keeping sidebar out no ui button required to open it**

That's just a few simple HTML/CSS edits.

**Comment by TConX** [comment]
Sidebar is now static.

**Comment by christopher-dart** [comment]
Daniel, you're in charge of locating the KML data and having it appear on Google Maps. 

Cheers!

**Comment by dtfsheedy** [comment]
I'll have it done by Monday

**Comment by TConX** [comment]
Well Icons Colours are now changeable.

**Comment by TConX** [comment]
Wow, all of these are done.  Should have closed this one ages ago...
