### ISSUE TITLE
Import/Export Excel

### ISSUE THREAD

**Issue by jenniferjen** [Team-Avengineers/WellMap#40]
Import:
-Use xls library to read data from excel
-Use XLS.utils.sheet_to_json to obtain a javascript array
-Convert array into well map points on map => specifically this.the_map.layers[i].points[j]

Export:
-Backwards implementation of import

**Comment by pkusoglu** [comment]
Fixed excel parsing.

Map points (from excel file) can be pulled from excel sheets.

returnedData in the process_wb function (in ui.js) is the map points that are parsed from excel file.

**Comment by jenniferjen** [comment]
Seems to have stopped working I'm guessing one of the possible errors are related to it being in its own html file vs well_map.

**Comment by jenniferjen** [comment]
-Import working 
-Export under development

**Comment by jenniferjen** [comment]
-Import and Export works

**Comment by christopher-dart** [comment]
Great job guys!
