### ISSUE TITLE
Poster & Presentation (Task 7)

### ISSUE THREAD

**Issue by jenniferjen** [Team-Avengineers/WellMap#41]
Task Leads: Jennifer and John

TODO Items (will be updated frequently):
-Update with sections of poster  - DONE
-Team review, techincal specs, references -> Due Mar 20
-Call for print cost and time estimate -> Pickup available Tues Mar 24 (according to them)
-Get poster board asap (check bookstore before going elsewhere) - DONE => Will be given to Piril for safekeeping 
-Get rid of that nasty green - DONE
-Screenshots added - DONE

*Refer to final task schedule below*

**Comment by jenniferjen** [comment]
-New folder created in drive => Task 7
-Poster template added

**Comment by jenniferjen** [comment]
Preliminary Task schedule (subject to change):
-Mar 16 decide what information to be added
-Mar 22 create draft (through drive)
-Mar 23-25 edit review by team
-Mar 27 finalization of template
-Mar 30 coordinate printing schedule and assembling poster 
-Apr 3 poster complete 
-Apr 7 Capstone design fair

**Comment by jenniferjen** [comment]
Important note on resolution: (for 48x36)
High quality - 14400x10800 ppi
Standard - 7200x5400 ppi

**Comment by jenniferjen** [comment]
Printing at UofC:
http://imagine.ucalgary.ca/files/imagine/freeflow-gettingstarted-documentation.pdf

**Comment by jenniferjen** [comment]
Best deal off campus:
http://printcalgary.com/index.php 
PROMO: Awesome Calgary
Price: 36" x 48"  $36 - 5 per person
http://printcalgary.com/products_large_posters.php

**Comment by pkusoglu** [comment]
I heard there's a huge lineup for poster printing at the library so I guess
it's better to be quick. But I definitely don't mind splitting the money
for off campus printing.

Piril

**Comment by jenniferjen** [comment]
Final Task schedule:
-Mar 16 decide what information to be added - Jen & John - DONE
-Mar 16 draft created - Jen & John - DONE
-Mar 16-20 edit review - Team 
-Mar 20 poster finalized (through drive) - Jen & John
-Mar 21-23 print poster (off-campus) - John
Dates below subject to change:
-Mar 23-27 assemble poster (this includes reprint/poster pickup) - Jen & John 
-Mar 30 poster complete
-Apr 7 Capstone design fair

**Comment by jenniferjen** [comment]
Poster is with Piril and is ready for the fair
