### ISSUE TITLE
todo issue 42

### ISSUE THREAD

**Issue by benibishi** [Team-Avengineers/WellMap#42]
the plus button makes a title for the list only thing we have to do is
- import selected icons to the new list we create 
functions added
- controller.js addList(name) creates a list with a title on the sidebar
- ui.js  line 256 modal function to make the button-addlist functional

**Comment by christopher-dart** [comment]
Check it out, Toss has already been working on the issue.

**Comment by pkusoglu** [comment]
If Toss is already working on this issue, I will excuse myself to move on to the Task 5 responsibilities and the presentation starting tomorrow.
Thank you

**Comment by benibishi** [comment]
for this issue as far as i can see what it says on the product scope i will reference it as well
the ability to create multiple maps and lists. This will be necessary for focusing on different regions on a case-by-case scenario 

thanks to toss that he is still doing a good job completed this issue
Thx again toss

**Comment by TConX** [comment]
I've really got to do a better job of closing issues after I solve the problem...
